#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Yorsh.Resource", IsApplication=true)]

namespace Yorsh
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Yorsh.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Yorsh.Resource.String.Hello;
			global::Xamarin.InAppBilling.Resource.String.library_name = global::Yorsh.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f090007
			public const int AndSuddenly = 2131296263;
			
			// aapt resource value: 0x7f090003
			public const int Bear = 2131296259;
			
			// aapt resource value: 0x7f090006
			public const int HowToPlay = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int MakeThis = 2131296258;
			
			// aapt resource value: 0x7f090000
			public const int Refuse = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int RefuseAndMove = 2131296257;
			
			// aapt resource value: 0x7f090004
			public const int RulesCirle = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int ShortAboutGame = 2131296261;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int com_facebook_auxiliary_view_position = 2130771972;
			
			// aapt resource value: 0x7f010006
			public const int com_facebook_confirm_logout = 2130771974;
			
			// aapt resource value: 0x7f010000
			public const int com_facebook_foreground_color = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int com_facebook_horizontal_alignment = 2130771973;
			
			// aapt resource value: 0x7f01000b
			public const int com_facebook_is_cropped = 2130771979;
			
			// aapt resource value: 0x7f010007
			public const int com_facebook_login_text = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int com_facebook_logout_text = 2130771976;
			
			// aapt resource value: 0x7f010001
			public const int com_facebook_object_id = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int com_facebook_object_type = 2130771970;
			
			// aapt resource value: 0x7f01000a
			public const int com_facebook_preset_size = 2130771978;
			
			// aapt resource value: 0x7f010003
			public const int com_facebook_style = 2130771971;
			
			// aapt resource value: 0x7f010009
			public const int com_facebook_tooltip_mode = 2130771977;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060014
			public const int black = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int bonus_bg = 2131099670;
			
			// aapt resource value: 0x7f06000d
			public const int bonus_blue = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int bonus_green = 2131099662;
			
			// aapt resource value: 0x7f06001b
			public const int button_disabled = 2131099675;
			
			// aapt resource value: 0x7f06001c
			public const int button_shadow_gray = 2131099676;
			
			// aapt resource value: 0x7f06001d
			public const int button_shadow_gray_text = 2131099677;
			
			// aapt resource value: 0x7f06001a
			public const int button_text_disabled = 2131099674;
			
			// aapt resource value: 0x7f060000
			public const int com_facebook_blue = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int com_facebook_button_background_color = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int com_facebook_button_background_color_disabled = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int com_facebook_button_background_color_pressed = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int com_facebook_button_like_background_color_selected = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int com_facebook_button_login_silver_background_color = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int com_facebook_button_login_silver_background_color_pressed = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int com_facebook_button_send_background_color = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int com_facebook_button_send_background_color_pressed = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int com_facebook_likeboxcountview_border_color = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int com_facebook_likeboxcountview_text_color = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int com_facebook_likeview_text_color = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int com_facebook_share_button_text_color = 2131099660;
			
			// aapt resource value: 0x7f060019
			public const int name_black = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int position_gray = 2131099672;
			
			// aapt resource value: 0x7f060017
			public const int pressed_text_color = 2131099671;
			
			// aapt resource value: 0x7f060010
			public const int task_progress_bg = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int task_progress_black = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int task_progress_green = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int task_progress_red = 2131099667;
			
			// aapt resource value: 0x7f06000f
			public const int tournament_green = 2131099663;
			
			// aapt resource value: 0x7f060015
			public const int white = 2131099669;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070015
			public const int ActionBar_Size = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int ActionBar_TitleMargin = 2131165206;
			
			// aapt resource value: 0x7f070014
			public const int ActionBar_TitleSize = 2131165204;
			
			// aapt resource value: 0x7f070033
			public const int AddNewPlayers_buttonHeight = 2131165235;
			
			// aapt resource value: 0x7f070031
			public const int AddNewPlayers_buttonTextSize = 2131165233;
			
			// aapt resource value: 0x7f070034
			public const int AddNewPlayers_buttonWidth = 2131165236;
			
			// aapt resource value: 0x7f070036
			public const int AddNewPlayers_editTextPadding = 2131165238;
			
			// aapt resource value: 0x7f070030
			public const int AddNewPlayers_editTextSize = 2131165232;
			
			// aapt resource value: 0x7f070032
			public const int AddNewPlayers_imageSize = 2131165234;
			
			// aapt resource value: 0x7f070035
			public const int AddNewPlayers_padding = 2131165237;
			
			// aapt resource value: 0x7f07002c
			public const int AddPlayerItem_imageSize = 2131165228;
			
			// aapt resource value: 0x7f07002f
			public const int AddPlayerItem_isPlayTextSize = 2131165231;
			
			// aapt resource value: 0x7f070028
			public const int AddPlayerItem_marginLeft = 2131165224;
			
			// aapt resource value: 0x7f070029
			public const int AddPlayerItem_marginRight = 2131165225;
			
			// aapt resource value: 0x7f07002e
			public const int AddPlayerItem_nameTextSize = 2131165230;
			
			// aapt resource value: 0x7f07002a
			public const int AddPlayerItem_paddingBottom = 2131165226;
			
			// aapt resource value: 0x7f07002b
			public const int AddPlayerItem_paddingTop = 2131165227;
			
			// aapt resource value: 0x7f07002d
			public const int AddPlayerItem_removeLayoutSize = 2131165229;
			
			// aapt resource value: 0x7f070081
			public const int Autorize_ButtonHeigt = 2131165313;
			
			// aapt resource value: 0x7f070082
			public const int Autorize_ButtonTextSize = 2131165314;
			
			// aapt resource value: 0x7f070083
			public const int Autorize_Margin = 2131165315;
			
			// aapt resource value: 0x7f070058
			public const int Bonus_BonusNameTextSize = 2131165272;
			
			// aapt resource value: 0x7f070057
			public const int Bonus_BonusNameTextWidth = 2131165271;
			
			// aapt resource value: 0x7f07005a
			public const int Bonus_ButtonHeight = 2131165274;
			
			// aapt resource value: 0x7f070059
			public const int Bonus_ButtonWidth = 2131165273;
			
			// aapt resource value: 0x7f070055
			public const int Bonus_CongratsPadingTop = 2131165269;
			
			// aapt resource value: 0x7f070054
			public const int Bonus_CongratsTextSize = 2131165268;
			
			// aapt resource value: 0x7f070050
			public const int Bonus_ContentPadding = 2131165264;
			
			// aapt resource value: 0x7f070051
			public const int Bonus_ImageHeight = 2131165265;
			
			// aapt resource value: 0x7f070052
			public const int Bonus_ImageWidth = 2131165266;
			
			// aapt resource value: 0x7f070053
			public const int Bonus_MarginBottom = 2131165267;
			
			// aapt resource value: 0x7f070056
			public const int Bonus_YouWonBonusTextSize = 2131165270;
			
			// aapt resource value: 0x7f070077
			public const int ChoosePhotoButton_Height = 2131165303;
			
			// aapt resource value: 0x7f070076
			public const int ChoosePhotoButton_MarginBottom = 2131165302;
			
			// aapt resource value: 0x7f070075
			public const int ChoosePhotoButton_TextSize = 2131165301;
			
			// aapt resource value: 0x7f070078
			public const int ChoosePhotoLayer_Padding = 2131165304;
			
			// aapt resource value: 0x7f070018
			public const int ContentMarginLeftRight = 2131165208;
			
			// aapt resource value: 0x7f070019
			public const int ContentMarginTopBottom = 2131165209;
			
			// aapt resource value: 0x7f070017
			public const int Dialog_MinWidth = 2131165207;
			
			// aapt resource value: 0x7f07007d
			public const int DialorRatingButton_Height = 2131165309;
			
			// aapt resource value: 0x7f07007c
			public const int DialorRatingButton_TextSize = 2131165308;
			
			// aapt resource value: 0x7f07007b
			public const int DialorRatingLayout_MarginRightLeft = 2131165307;
			
			// aapt resource value: 0x7f07007a
			public const int DialorRatingLayout_MarginTop = 2131165306;
			
			// aapt resource value: 0x7f070079
			public const int DialorRating_TextViewSize = 2131165305;
			
			// aapt resource value: 0x7f070087
			public const int EditText_ButtonHeight = 2131165319;
			
			// aapt resource value: 0x7f070086
			public const int EditText_EditHeight = 2131165318;
			
			// aapt resource value: 0x7f070084
			public const int EditText_Margins = 2131165316;
			
			// aapt resource value: 0x7f070085
			public const int EditText_TextSize = 2131165317;
			
			// aapt resource value: 0x7f070065
			public const int FirstPalyerItem_HalfImageSize = 2131165285;
			
			// aapt resource value: 0x7f070064
			public const int FirstPlayerItem_ImageSize = 2131165284;
			
			// aapt resource value: 0x7f070048
			public const int Game_BottomButtonHeight = 2131165256;
			
			// aapt resource value: 0x7f070049
			public const int Game_BottomButtonLeftRightMargin = 2131165257;
			
			// aapt resource value: 0x7f07004a
			public const int Game_BottomButtonTextSize = 2131165258;
			
			// aapt resource value: 0x7f070047
			public const int Game_BottomButtonWidth = 2131165255;
			
			// aapt resource value: 0x7f070045
			public const int Game_CardButtonHeight = 2131165253;
			
			// aapt resource value: 0x7f070046
			public const int Game_CardButtonWidth = 2131165254;
			
			// aapt resource value: 0x7f07003b
			public const int Game_ContentPaddingLeftRight = 2131165243;
			
			// aapt resource value: 0x7f07003c
			public const int Game_ContentPaddingTopBottom = 2131165244;
			
			// aapt resource value: 0x7f07004b
			public const int Game_PointsLayoutHeight = 2131165259;
			
			// aapt resource value: 0x7f07004c
			public const int Game_PointsSize = 2131165260;
			
			// aapt resource value: 0x7f07004d
			public const int Game_PointsTextSize = 2131165261;
			
			// aapt resource value: 0x7f070040
			public const int Game_TopBarCountScoreTextSize = 2131165248;
			
			// aapt resource value: 0x7f07003d
			public const int Game_TopBarHeight = 2131165245;
			
			// aapt resource value: 0x7f07003e
			public const int Game_TopBarImageSize = 2131165246;
			
			// aapt resource value: 0x7f07003f
			public const int Game_TopBarMargin = 2131165247;
			
			// aapt resource value: 0x7f070043
			public const int Game_TopBarPlayerNameTextSize = 2131165251;
			
			// aapt resource value: 0x7f070044
			public const int Game_TopBarPlayerPositionTextSize = 2131165252;
			
			// aapt resource value: 0x7f070041
			public const int Game_TopBarScoreTextSize = 2131165249;
			
			// aapt resource value: 0x7f070042
			public const int Game_TopBarTextMargin = 2131165250;
			
			// aapt resource value: 0x7f07004e
			public const int Game_x2Size = 2131165262;
			
			// aapt resource value: 0x7f07004f
			public const int Game_x2TextSize = 2131165263;
			
			// aapt resource value: 0x7f070037
			public const int ImageCard_MarginBottom = 2131165239;
			
			// aapt resource value: 0x7f07003a
			public const int ImageCard_TextHeight = 2131165242;
			
			// aapt resource value: 0x7f070039
			public const int ImageCard_TextPadding = 2131165241;
			
			// aapt resource value: 0x7f070038
			public const int ImageCard_TextSize = 2131165240;
			
			// aapt resource value: 0x7f07001d
			public const int MainMenu_linkMarginBottom = 2131165213;
			
			// aapt resource value: 0x7f07001c
			public const int MainMenu_linkMarginTop = 2131165212;
			
			// aapt resource value: 0x7f07001b
			public const int MainMenu_linkSize = 2131165211;
			
			// aapt resource value: 0x7f07001a
			public const int MainMenu_logoSize = 2131165210;
			
			// aapt resource value: 0x7f070023
			public const int MainMenu_plusTaskButtonHeight = 2131165219;
			
			// aapt resource value: 0x7f070024
			public const int MainMenu_plusTaskButtonTextSize = 2131165220;
			
			// aapt resource value: 0x7f070022
			public const int MainMenu_plusTaskButtonWidth = 2131165218;
			
			// aapt resource value: 0x7f070020
			public const int MainMenu_startButtonHeight = 2131165216;
			
			// aapt resource value: 0x7f070021
			public const int MainMenu_startButtonMarginBottom = 2131165217;
			
			// aapt resource value: 0x7f07001e
			public const int MainMenu_startButtonTextSize = 2131165214;
			
			// aapt resource value: 0x7f07001f
			public const int MainMenu_startButtonWidth = 2131165215;
			
			// aapt resource value: 0x7f070080
			public const int PickPlayerDialog_ListView_MarginS = 2131165312;
			
			// aapt resource value: 0x7f07007e
			public const int PickPlayerDialog_TextView_Height = 2131165310;
			
			// aapt resource value: 0x7f07007f
			public const int PickPlayerDialog_TextView_Size = 2131165311;
			
			// aapt resource value: 0x7f07006f
			public const int PlayerLeadText_Size = 2131165295;
			
			// aapt resource value: 0x7f070070
			public const int PlayerNameText_Size = 2131165296;
			
			// aapt resource value: 0x7f070071
			public const int PlayerScoreText_Size = 2131165297;
			
			// aapt resource value: 0x7f070025
			public const int PlayersList_buttonHeight = 2131165221;
			
			// aapt resource value: 0x7f070027
			public const int PlayersList_buttonTextSize = 2131165223;
			
			// aapt resource value: 0x7f070026
			public const int PlayersList_buttonWidth = 2131165222;
			
			// aapt resource value: 0x7f070072
			public const int ResultGameButton_Text_Size = 2131165298;
			
			// aapt resource value: 0x7f070073
			public const int ResultGameList_MarginBotom = 2131165299;
			
			// aapt resource value: 0x7f070074
			public const int ResultGameList_MarginLeftRight = 2131165300;
			
			// aapt resource value: 0x7f070013
			public const int RoundedCorners = 2131165203;
			
			// aapt resource value: 0x7f07006e
			public const int RuleFragment_ContainerTextSize = 2131165294;
			
			// aapt resource value: 0x7f07006d
			public const int RuleFragment_HeaderTextMarginTopBottom = 2131165293;
			
			// aapt resource value: 0x7f07006c
			public const int RuleFragment_HeaderTextSize = 2131165292;
			
			// aapt resource value: 0x7f07006b
			public const int RuleFragment_ImageViewHeight = 2131165291;
			
			// aapt resource value: 0x7f070067
			public const int RuleFragment_LayoutMarginBottom = 2131165287;
			
			// aapt resource value: 0x7f070069
			public const int RuleFragment_LayoutMarginLeftRight = 2131165289;
			
			// aapt resource value: 0x7f070068
			public const int RuleFragment_LayoutMarginTop = 2131165288;
			
			// aapt resource value: 0x7f07006a
			public const int RuleFragment_LayoutPadding = 2131165290;
			
			// aapt resource value: 0x7f070066
			public const int RuleFragment_ScrollImageMarginBottom = 2131165286;
			
			// aapt resource value: 0x7f07005f
			public const int TaskProgress_ContinueButtonHeight = 2131165279;
			
			// aapt resource value: 0x7f070060
			public const int TaskProgress_ContinueButtonWidth = 2131165280;
			
			// aapt resource value: 0x7f070062
			public const int TaskProgress_CurrentScoreTextSize = 2131165282;
			
			// aapt resource value: 0x7f07005e
			public const int TaskProgress_DescTextSize = 2131165278;
			
			// aapt resource value: 0x7f070063
			public const int TaskProgress_EndDescTextSize = 2131165283;
			
			// aapt resource value: 0x7f07005c
			public const int TaskProgress_MarginBottom = 2131165276;
			
			// aapt resource value: 0x7f07005b
			public const int TaskProgress_MarginTop = 2131165275;
			
			// aapt resource value: 0x7f070061
			public const int TaskProgress_ScoreLayoutHeight = 2131165281;
			
			// aapt resource value: 0x7f07005d
			public const int TaskProgress_TitleTextSize = 2131165277;
			
			// aapt resource value: 0x7f070000
			public const int com_facebook_likeboxcountview_border_radius = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int com_facebook_likeboxcountview_border_width = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int com_facebook_likeboxcountview_caret_height = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int com_facebook_likeboxcountview_caret_width = 2131165187;
			
			// aapt resource value: 0x7f070004
			public const int com_facebook_likeboxcountview_text_padding = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int com_facebook_likeboxcountview_text_size = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int com_facebook_likeview_edge_padding = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int com_facebook_likeview_internal_padding = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int com_facebook_likeview_text_size = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int com_facebook_profilepictureview_preset_size_large = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int com_facebook_profilepictureview_preset_size_normal = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int com_facebook_profilepictureview_preset_size_small = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int com_facebook_share_button_compound_drawable_padding = 2131165196;
			
			// aapt resource value: 0x7f07000d
			public const int com_facebook_share_button_padding_bottom = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int com_facebook_share_button_padding_left = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int com_facebook_share_button_padding_right = 2131165199;
			
			// aapt resource value: 0x7f070010
			public const int com_facebook_share_button_padding_top = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int com_facebook_share_button_text_size = 2131165201;
			
			// aapt resource value: 0x7f070012
			public const int com_facebook_tooltip_horizontal_padding = 2131165202;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_new_player = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add_player_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int add_player_button_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int add_player_button_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int back_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int back_button_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int back_button_selector = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bonus = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bonus_button_selector = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bonus_sale = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bonus_store_icon = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int cancel_button = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int card_backside = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int choose_from_contacts = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int circle_shape = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int com_facebook_button_background = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int com_facebook_button_icon = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int com_facebook_button_like_background = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int com_facebook_button_like_icon_selected = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int com_facebook_button_login_silver_background = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int com_facebook_button_send_background = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int com_facebook_button_send_icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int com_facebook_close = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int com_facebook_profile_picture_blank_portrait = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int com_facebook_profile_picture_blank_square = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int com_facebook_tooltip_black_background = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int com_facebook_tooltip_black_bottomnub = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int com_facebook_tooltip_black_topnub = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int com_facebook_tooltip_black_xout = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int com_facebook_tooltip_blue_background = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int com_facebook_tooltip_blue_bottomnub = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int com_facebook_tooltip_blue_topnub = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int com_facebook_tooltip_blue_xout = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int continue_button = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int continue_pressed = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int delete_button = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int done = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int fb72 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int fbicon = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int first_player = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int first_player_icon = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int game_background = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int home_button = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int Icon = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int iq_bg = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int light_bottom = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int light_top = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int logo = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int messenger_bubble_large_blue = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int messenger_bubble_large_white = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int messenger_bubble_small_blue = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int messenger_bubble_small_white = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int messenger_button_blue_bg_round = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int messenger_button_blue_bg_selector = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int messenger_button_send_round_shadow = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int messenger_button_white_bg_round = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int messenger_button_white_bg_selector = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int photo_default = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int plus_tasks_button = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int points = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ready_button = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ready_label_enable = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int remove_adb = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int round_rect_shape_grey_background = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int round_rect_shape_white_background = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int round_rect_shape_white_border = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int rules_button = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int rules_one_page = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int rules_one_sroll_page = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int rules_three_page = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int rules_three_sroll_page = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int rules_two_page = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int rules_two_sroll_page = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int shadow = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int shared = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int shop_background_bottomlight = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int shop_background_toplight = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int shop_bonus_10 = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int shop_bonus_30 = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int shop_bonus_all = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int shop_bonus_background = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int shop_more_background = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int shop_task_10 = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int shop_task_100 = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int shop_task_30 = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int shop_task_70 = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int shop_task_all = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int shop_task_background = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int splash = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int splash_screen = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int start_game_button = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int start_new_game_button = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int table_button = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int table_list_background = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int task_sale = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int task_store_icon = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int taskprogress_background = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int tw72 = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int twicon = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int vk = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int vk72 = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int x2 = 2130837606;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0047
			public const int BoardGame = 2131361863;
			
			// aapt resource value: 0x7f0a004a
			public const int PlusCards = 2131361866;
			
			// aapt resource value: 0x7f0a0049
			public const int Rules = 2131361865;
			
			// aapt resource value: 0x7f0a0048
			public const int StartGame = 2131361864;
			
			// aapt resource value: 0x7f0a0039
			public const int SumbitShare = 2131361849;
			
			// aapt resource value: 0x7f0a0038
			public const int TextShare = 2131361848;
			
			// aapt resource value: 0x7f0a0016
			public const int TextView01 = 2131361814;
			
			// aapt resource value: 0x7f0a0083
			public const int addPlayer = 2131361923;
			
			// aapt resource value: 0x7f0a000c
			public const int automatic = 2131361804;
			
			// aapt resource value: 0x7f0a006f
			public const int bonusListView = 2131361903;
			
			// aapt resource value: 0x7f0a0027
			public const int bonusText = 2131361831;
			
			// aapt resource value: 0x7f0a0006
			public const int bottom = 2131361798;
			
			// aapt resource value: 0x7f0a0003
			public const int box_count = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int button = 2131361796;
			
			// aapt resource value: 0x7f0a007f
			public const int button1 = 2131361919;
			
			// aapt resource value: 0x7f0a0035
			public const int buttonEasy = 2131361845;
			
			// aapt resource value: 0x7f0a005e
			public const int buttonFb = 2131361886;
			
			// aapt resource value: 0x7f0a0053
			public const int buttonFrameLayout = 2131361875;
			
			// aapt resource value: 0x7f0a0064
			public const int buttonLayout = 2131361892;
			
			// aapt resource value: 0x7f0a0037
			public const int buttonNo = 2131361847;
			
			// aapt resource value: 0x7f0a005f
			public const int buttonTw = 2131361887;
			
			// aapt resource value: 0x7f0a005d
			public const int buttonVk = 2131361885;
			
			// aapt resource value: 0x7f0a0036
			public const int buttonYester = 2131361846;
			
			// aapt resource value: 0x7f0a0017
			public const int cancelButton = 2131361815;
			
			// aapt resource value: 0x7f0a0009
			public const int center = 2131361801;
			
			// aapt resource value: 0x7f0a007c
			public const int changeCountScoreText = 2131361916;
			
			// aapt resource value: 0x7f0a0015
			public const int chooseFromContButton = 2131361813;
			
			// aapt resource value: 0x7f0a0029
			public const int choosePhotoButton = 2131361833;
			
			// aapt resource value: 0x7f0a002b
			public const int choosePlayer = 2131361835;
			
			// aapt resource value: 0x7f0a003f
			public const int circle_crop = 2131361855;
			
			// aapt resource value: 0x7f0a002e
			public const int com_facebook_body_frame = 2131361838;
			
			// aapt resource value: 0x7f0a0030
			public const int com_facebook_button_xout = 2131361840;
			
			// aapt resource value: 0x7f0a002c
			public const int com_facebook_fragment_container = 2131361836;
			
			// aapt resource value: 0x7f0a002d
			public const int com_facebook_login_activity_progress_bar = 2131361837;
			
			// aapt resource value: 0x7f0a0032
			public const int com_facebook_tooltip_bubble_view_bottom_pointer = 2131361842;
			
			// aapt resource value: 0x7f0a0031
			public const int com_facebook_tooltip_bubble_view_text_body = 2131361841;
			
			// aapt resource value: 0x7f0a002f
			public const int com_facebook_tooltip_bubble_view_top_pointer = 2131361839;
			
			// aapt resource value: 0x7f0a0055
			public const int completeGameButton = 2131361877;
			
			// aapt resource value: 0x7f0a0018
			public const int confirmButton = 2131361816;
			
			// aapt resource value: 0x7f0a0024
			public const int congrats = 2131361828;
			
			// aapt resource value: 0x7f0a0043
			public const int contentFrameLayout = 2131361859;
			
			// aapt resource value: 0x7f0a0026
			public const int continueButton = 2131361830;
			
			// aapt resource value: 0x7f0a007e
			public const int currentScoreText = 2131361918;
			
			// aapt resource value: 0x7f0a0082
			public const int customActionButton = 2131361922;
			
			// aapt resource value: 0x7f0a007b
			public const int descLayout = 2131361915;
			
			// aapt resource value: 0x7f0a000d
			public const int display_always = 2131361805;
			
			// aapt resource value: 0x7f0a001a
			public const int doneImage = 2131361818;
			
			// aapt resource value: 0x7f0a0080
			public const int editText1 = 2131361920;
			
			// aapt resource value: 0x7f0a007d
			public const int endDescriptionText = 2131361917;
			
			// aapt resource value: 0x7f0a003b
			public const int greeting = 2131361851;
			
			// aapt resource value: 0x7f0a0058
			public const int imageBackgroundRules = 2131361880;
			
			// aapt resource value: 0x7f0a0071
			public const int imageButThreeOne = 2131361905;
			
			// aapt resource value: 0x7f0a0044
			public const int imageCardView = 2131361860;
			
			// aapt resource value: 0x7f0a004d
			public const int imagePickPlayer = 2131361869;
			
			// aapt resource value: 0x7f0a005b
			public const int imageScroll = 2131361883;
			
			// aapt resource value: 0x7f0a0023
			public const int imageView = 2131361827;
			
			// aapt resource value: 0x7f0a0007
			public const int inline = 2131361799;
			
			// aapt resource value: 0x7f0a001d
			public const int isPlayText = 2131361821;
			
			// aapt resource value: 0x7f0a000f
			public const int large = 2131361807;
			
			// aapt resource value: 0x7f0a0075
			public const int layout = 2131361909;
			
			// aapt resource value: 0x7f0a0040
			public const int leadText = 2131361856;
			
			// aapt resource value: 0x7f0a000a
			public const int left = 2131361802;
			
			// aapt resource value: 0x7f0a0074
			public const int light_bottom = 2131361908;
			
			// aapt resource value: 0x7f0a0033
			public const int linearLayout1 = 2131361843;
			
			// aapt resource value: 0x7f0a0020
			public const int login = 2131361824;
			
			// aapt resource value: 0x7f0a0046
			public const int logoImage = 2131361862;
			
			// aapt resource value: 0x7f0a003a
			public const int main_ui_container = 2131361850;
			
			// aapt resource value: 0x7f0a0028
			public const int makePhotoButton = 2131361832;
			
			// aapt resource value: 0x7f0a0066
			public const int makeThisButton = 2131361894;
			
			// aapt resource value: 0x7f0a004b
			public const int messenger_send_button = 2131361867;
			
			// aapt resource value: 0x7f0a004e
			public const int namePickPlayer = 2131361870;
			
			// aapt resource value: 0x7f0a000e
			public const int never_display = 2131361806;
			
			// aapt resource value: 0x7f0a0010
			public const int normal = 2131361808;
			
			// aapt resource value: 0x7f0a0000
			public const int open_graph = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int page = 2131361793;
			
			// aapt resource value: 0x7f0a0021
			public const int password = 2131361825;
			
			// aapt resource value: 0x7f0a0013
			public const int playerImage = 2131361811;
			
			// aapt resource value: 0x7f0a004f
			public const int playerInGameImage = 2131361871;
			
			// aapt resource value: 0x7f0a0050
			public const int playerInGameName = 2131361872;
			
			// aapt resource value: 0x7f0a0051
			public const int playerInGamePostion = 2131361873;
			
			// aapt resource value: 0x7f0a0052
			public const int playerInGameScore = 2131361874;
			
			// aapt resource value: 0x7f0a0012
			public const int playerLayout = 2131361810;
			
			// aapt resource value: 0x7f0a002a
			public const int playerList = 2131361834;
			
			// aapt resource value: 0x7f0a0014
			public const int playerName = 2131361812;
			
			// aapt resource value: 0x7f0a001c
			public const int playerNameLayout = 2131361820;
			
			// aapt resource value: 0x7f0a004c
			public const int playerPickList = 2131361868;
			
			// aapt resource value: 0x7f0a0042
			public const int playerScore = 2131361858;
			
			// aapt resource value: 0x7f0a0057
			public const int playerTournamentListView = 2131361879;
			
			// aapt resource value: 0x7f0a001f
			public const int playersList = 2131361823;
			
			// aapt resource value: 0x7f0a0068
			public const int points = 2131361896;
			
			// aapt resource value: 0x7f0a003e
			public const int postPhotoButton = 2131361854;
			
			// aapt resource value: 0x7f0a003d
			public const int postStatusUpdateButton = 2131361853;
			
			// aapt resource value: 0x7f0a0078
			public const int priceText = 2131361912;
			
			// aapt resource value: 0x7f0a003c
			public const int profilePicture = 2131361852;
			
			// aapt resource value: 0x7f0a0065
			public const int refuseButton = 2131361893;
			
			// aapt resource value: 0x7f0a0054
			public const int relativeLayout = 2131361876;
			
			// aapt resource value: 0x7f0a001b
			public const int removeButton = 2131361819;
			
			// aapt resource value: 0x7f0a0019
			public const int removeLayout = 2131361817;
			
			// aapt resource value: 0x7f0a000b
			public const int right = 2131361803;
			
			// aapt resource value: 0x7f0a0077
			public const int saleImageView = 2131361911;
			
			// aapt resource value: 0x7f0a0061
			public const int scoreLayout = 2131361889;
			
			// aapt resource value: 0x7f0a0062
			public const int scoreString = 2131361890;
			
			// aapt resource value: 0x7f0a0041
			public const int scoreText = 2131361857;
			
			// aapt resource value: 0x7f0a0063
			public const int separator = 2131361891;
			
			// aapt resource value: 0x7f0a0056
			public const int shareButton = 2131361878;
			
			// aapt resource value: 0x7f0a0011
			public const int small = 2131361809;
			
			// aapt resource value: 0x7f0a0005
			public const int standard = 2131361797;
			
			// aapt resource value: 0x7f0a0060
			public const int startGameLayout = 2131361888;
			
			// aapt resource value: 0x7f0a001e
			public const int startPlayButton = 2131361822;
			
			// aapt resource value: 0x7f0a007a
			public const int statusDescriptionText = 2131361914;
			
			// aapt resource value: 0x7f0a0079
			public const int statusTitleText = 2131361913;
			
			// aapt resource value: 0x7f0a0076
			public const int storeButton = 2131361910;
			
			// aapt resource value: 0x7f0a0022
			public const int sumbit = 2131361826;
			
			// aapt resource value: 0x7f0a0084
			public const int tableButton = 2131361924;
			
			// aapt resource value: 0x7f0a006a
			public const int tableShop = 2131361898;
			
			// aapt resource value: 0x7f0a0067
			public const int taskImageButton = 2131361895;
			
			// aapt resource value: 0x7f0a006c
			public const int taskListView = 2131361900;
			
			// aapt resource value: 0x7f0a0045
			public const int textCard = 2131361861;
			
			// aapt resource value: 0x7f0a005a
			public const int textContainer = 2131361882;
			
			// aapt resource value: 0x7f0a006b
			public const int textDescription = 2131361899;
			
			// aapt resource value: 0x7f0a0073
			public const int textDescriptionThreeOne = 2131361907;
			
			// aapt resource value: 0x7f0a0072
			public const int textDescriptionThreeTwo = 2131361906;
			
			// aapt resource value: 0x7f0a006e
			public const int textDescriptionTwo = 2131361902;
			
			// aapt resource value: 0x7f0a0059
			public const int textHeader = 2131361881;
			
			// aapt resource value: 0x7f0a0070
			public const int textHeaderThree = 2131361904;
			
			// aapt resource value: 0x7f0a006d
			public const int textHeaderTwo = 2131361901;
			
			// aapt resource value: 0x7f0a0034
			public const int textView1 = 2131361844;
			
			// aapt resource value: 0x7f0a0081
			public const int titleText = 2131361921;
			
			// aapt resource value: 0x7f0a0008
			public const int top = 2131361800;
			
			// aapt resource value: 0x7f0a0002
			public const int unknown = 2131361794;
			
			// aapt resource value: 0x7f0a005c
			public const int viewPager = 2131361884;
			
			// aapt resource value: 0x7f0a0069
			public const int x2 = 2131361897;
			
			// aapt resource value: 0x7f0a0025
			public const int youHaveBonus = 2131361829;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AddNewPlayer = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AddPlayerItem = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int AddPlayers = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Autorize = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Bonus = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ChoosePhoto = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ChoosePlayer = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int ChoosePlayerItem = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int com_facebook_activity_layout = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int com_facebook_login_fragment = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int com_facebook_tooltip_bubble = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int DialogRating = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int EditText = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int Facebook = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int FirstPlayerItem = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int ImageCard = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int MainMenu = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int messenger_button_send_blue_large = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int messenger_button_send_blue_round = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int messenger_button_send_blue_small = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int messenger_button_send_white_large = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int messenger_button_send_white_round = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int messenger_button_send_white_small = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int MosDialog = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int PickPlayerDialog = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int PickPlayerItem = 2130968601;
			
			// aapt resource value: 0x7f04001a
			public const int PlayerInGameItem = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int PlayerItem = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int ResultsGame = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int RuleFragment = 2130968605;
			
			// aapt resource value: 0x7f04001e
			public const int Rules = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int ShareSoc = 2130968607;
			
			// aapt resource value: 0x7f040020
			public const int Splash = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int StartGame = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int Store = 2130968610;
			
			// aapt resource value: 0x7f040023
			public const int StoreItem = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int TaskStatus = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int text = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int YorshActionBar = 2130968614;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050024
			public const int AddNewPlayerLowCaseString = 2131034148;
			
			// aapt resource value: 0x7f050025
			public const int AddNewPlayerString = 2131034149;
			
			// aapt resource value: 0x7f050013
			public const int ApplicationName = 2131034131;
			
			// aapt resource value: 0x7f05003c
			public const int AreYouLikeString = 2131034172;
			
			// aapt resource value: 0x7f050029
			public const int AreYouShureString = 2131034153;
			
			// aapt resource value: 0x7f050014
			public const int BoardGameString = 2131034132;
			
			// aapt resource value: 0x7f05001d
			public const int BuyString = 2131034141;
			
			// aapt resource value: 0x7f050045
			public const int CancelString = 2131034181;
			
			// aapt resource value: 0x7f050023
			public const int ChooseFromContactString = 2131034147;
			
			// aapt resource value: 0x7f05002f
			public const int ChooseFromGalleryString = 2131034159;
			
			// aapt resource value: 0x7f050038
			public const int CompleteGameString = 2131034168;
			
			// aapt resource value: 0x7f050046
			public const int ConfirmString = 2131034182;
			
			// aapt resource value: 0x7f050041
			public const int CongratString = 2131034177;
			
			// aapt resource value: 0x7f050033
			public const int ContinueString = 2131034163;
			
			// aapt resource value: 0x7f05003e
			public const int EasyString = 2131034174;
			
			// aapt resource value: 0x7f05003d
			public const int EstimateUsString = 2131034173;
			
			// aapt resource value: 0x7f050028
			public const int GameString = 2131034152;
			
			// aapt resource value: 0x7f050018
			public const int GoToMosigraSite = 2131034136;
			
			// aapt resource value: 0x7f050048
			public const int GoToSaleString = 2131034184;
			
			// aapt resource value: 0x7f050047
			public const int GoToShopingString = 2131034183;
			
			// aapt resource value: 0x7f050012
			public const int Hello = 2131034130;
			
			// aapt resource value: 0x7f050020
			public const int IsNotPlayString = 2131034144;
			
			// aapt resource value: 0x7f05001f
			public const int IsPlayString = 2131034143;
			
			// aapt resource value: 0x7f05003f
			public const int LaterString = 2131034175;
			
			// aapt resource value: 0x7f050035
			public const int LeadString = 2131034165;
			
			// aapt resource value: 0x7f050027
			public const int MakePhotoString = 2131034151;
			
			// aapt resource value: 0x7f05002c
			public const int MakeThisString = 2131034156;
			
			// aapt resource value: 0x7f050039
			public const int NewGameString = 2131034169;
			
			// aapt resource value: 0x7f050040
			public const int NoFunString = 2131034176;
			
			// aapt resource value: 0x7f050021
			public const int NoNameString = 2131034145;
			
			// aapt resource value: 0x7f05002b
			public const int NoString = 2131034155;
			
			// aapt resource value: 0x7f050034
			public const int NotSupportCameraString = 2131034164;
			
			// aapt resource value: 0x7f050019
			public const int OpenSiteQuestionString = 2131034137;
			
			// aapt resource value: 0x7f050032
			public const int PickPlayerString = 2131034162;
			
			// aapt resource value: 0x7f050022
			public const int PlayerNameString = 2131034146;
			
			// aapt resource value: 0x7f05001e
			public const int PlayersString = 2131034142;
			
			// aapt resource value: 0x7f050043
			public const int PleaseSelectThePlayerString = 2131034179;
			
			// aapt resource value: 0x7f050017
			public const int PlusCardsString = 2131034135;
			
			// aapt resource value: 0x7f050030
			public const int PositionPlayerString = 2131034160;
			
			// aapt resource value: 0x7f050044
			public const int PressReadyButtonString = 2131034180;
			
			// aapt resource value: 0x7f05002d
			public const int RefuseString = 2131034157;
			
			// aapt resource value: 0x7f05003b
			public const int ResultsString = 2131034171;
			
			// aapt resource value: 0x7f05001c
			public const int RulesGameString = 2131034140;
			
			// aapt resource value: 0x7f050016
			public const int RulesString = 2131034134;
			
			// aapt resource value: 0x7f050031
			public const int ScoreString = 2131034161;
			
			// aapt resource value: 0x7f050037
			public const int ScoresString = 2131034167;
			
			// aapt resource value: 0x7f05003a
			public const int ShareString = 2131034170;
			
			// aapt resource value: 0x7f050026
			public const int StartGameButtonString = 2131034150;
			
			// aapt resource value: 0x7f050015
			public const int StartGameString = 2131034133;
			
			// aapt resource value: 0x7f05001b
			public const int TheLongestBonusString = 2131034139;
			
			// aapt resource value: 0x7f05001a
			public const int TheLongestTaskString = 2131034138;
			
			// aapt resource value: 0x7f05002e
			public const int TournirTableString = 2131034158;
			
			// aapt resource value: 0x7f050036
			public const int WinnerString = 2131034166;
			
			// aapt resource value: 0x7f05002a
			public const int YesString = 2131034154;
			
			// aapt resource value: 0x7f050042
			public const int YouHaveBonusString = 2131034178;
			
			// aapt resource value: 0x7f050056
			public const int app_id = 2131034198;
			
			// aapt resource value: 0x7f050049
			public const int cancelled = 2131034185;
			
			// aapt resource value: 0x7f050001
			public const int com_facebook_image_download_unknown_error = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int com_facebook_internet_permission_error_message = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int com_facebook_internet_permission_error_title = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int com_facebook_like_button_liked = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int com_facebook_like_button_not_liked = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int com_facebook_loading = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int com_facebook_loginview_cancel_action = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int com_facebook_loginview_log_in_button = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int com_facebook_loginview_log_in_button_long = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int com_facebook_loginview_log_out_action = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int com_facebook_loginview_log_out_button = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int com_facebook_loginview_logged_in_as = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int com_facebook_loginview_logged_in_using_facebook = 2131034125;
			
			// aapt resource value: 0x7f05000e
			public const int com_facebook_send_button_text = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int com_facebook_share_button_text = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int com_facebook_tooltip_default = 2131034128;
			
			// aapt resource value: 0x7f05004f
			public const int error = 2131034191;
			
			// aapt resource value: 0x7f050057
			public const int exception = 2131034199;
			
			// aapt resource value: 0x7f05004c
			public const int hello_user = 2131034188;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050011
			public const int messenger_send_button_text = 2131034129;
			
			// aapt resource value: 0x7f050053
			public const int no_friends_selected = 2131034195;
			
			// aapt resource value: 0x7f050054
			public const int no_place_selected = 2131034196;
			
			// aapt resource value: 0x7f05004b
			public const int ok = 2131034187;
			
			// aapt resource value: 0x7f05004a
			public const int permission_not_granted = 2131034186;
			
			// aapt resource value: 0x7f050051
			public const int photo_post = 2131034193;
			
			// aapt resource value: 0x7f050055
			public const int pick_seattle_place = 2131034197;
			
			// aapt resource value: 0x7f050050
			public const int status_update = 2131034192;
			
			// aapt resource value: 0x7f05004d
			public const int success = 2131034189;
			
			// aapt resource value: 0x7f05004e
			public const int successfully_posted_post = 2131034190;
			
			// aapt resource value: 0x7f050052
			public const int you_picked = 2131034194;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int MessengerButton = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int MessengerButton_Blue = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int MessengerButton_Blue_Large = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int MessengerButton_Blue_Small = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int MessengerButton_White = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int MessengerButton_White_Large = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int MessengerButton_White_Small = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int MessengerButtonText = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int MessengerButtonText_Blue = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int MessengerButtonText_Blue_Large = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int MessengerButtonText_Blue_Small = 2131230730;
			
			// aapt resource value: 0x7f08000b
			public const int MessengerButtonText_White = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int MessengerButtonText_White_Large = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int MessengerButtonText_White_Small = 2131230733;
			
			// aapt resource value: 0x7f080016
			public const int Theme_AppTheme = 2131230742;
			
			// aapt resource value: 0x7f080015
			public const int Theme_WithoutActionBar = 2131230741;
			
			// aapt resource value: 0x7f080017
			public const int WhiteActionBar = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int YourshDialog = 2131230744;
			
			// aapt resource value: 0x7f08000e
			public const int com_facebook_button = 2131230734;
			
			// aapt resource value: 0x7f08000f
			public const int com_facebook_button_like = 2131230735;
			
			// aapt resource value: 0x7f080010
			public const int com_facebook_button_send = 2131230736;
			
			// aapt resource value: 0x7f080011
			public const int com_facebook_button_share = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int com_facebook_loginview_default_style = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int com_facebook_loginview_silver_style = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int tooltip_bubble_text = 2131230740;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] com_facebook_like_view = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 4
			public const int com_facebook_like_view_com_facebook_auxiliary_view_position = 4;
			
			// aapt resource value: 0
			public const int com_facebook_like_view_com_facebook_foreground_color = 0;
			
			// aapt resource value: 5
			public const int com_facebook_like_view_com_facebook_horizontal_alignment = 5;
			
			// aapt resource value: 1
			public const int com_facebook_like_view_com_facebook_object_id = 1;
			
			// aapt resource value: 2
			public const int com_facebook_like_view_com_facebook_object_type = 2;
			
			// aapt resource value: 3
			public const int com_facebook_like_view_com_facebook_style = 3;
			
			public static int[] com_facebook_login_view = new int[] {
					2130771974,
					2130771975,
					2130771976,
					2130771977};
			
			// aapt resource value: 0
			public const int com_facebook_login_view_com_facebook_confirm_logout = 0;
			
			// aapt resource value: 1
			public const int com_facebook_login_view_com_facebook_login_text = 1;
			
			// aapt resource value: 2
			public const int com_facebook_login_view_com_facebook_logout_text = 2;
			
			// aapt resource value: 3
			public const int com_facebook_login_view_com_facebook_tooltip_mode = 3;
			
			public static int[] com_facebook_profile_picture_view = new int[] {
					2130771978,
					2130771979};
			
			// aapt resource value: 1
			public const int com_facebook_profile_picture_view_com_facebook_is_cropped = 1;
			
			// aapt resource value: 0
			public const int com_facebook_profile_picture_view_com_facebook_preset_size = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
