#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Yorsh.Resource", IsApplication=true)]

namespace Yorsh
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Resource.String.ApplicationName = global::Yorsh.Resource.String.ApplicationName;
			global::SQLite.Resource.String.Hello = global::Yorsh.Resource.String.Hello;
			global::Xamarin.InAppBilling.Resource.String.library_name = global::Yorsh.Resource.String.library_name;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f080007
			public const int AndSuddenly = 2131230727;
			
			// aapt resource value: 0x7f080003
			public const int Bear = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int HowToPlay = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int MakeThis = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int Refuse = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int RefuseAndMove = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int RulesCirle = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int ShortAboutGame = 2131230725;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f090007
			public const int black = 2131296263;
			
			// aapt resource value: 0x7f09000a
			public const int bonus_bg = 2131296266;
			
			// aapt resource value: 0x7f090000
			public const int bonus_blue = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int bonus_green = 2131296257;
			
			// aapt resource value: 0x7f09000f
			public const int button_disabled = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int button_shadow_gray = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int button_shadow_gray_text = 2131296273;
			
			// aapt resource value: 0x7f09000e
			public const int button_text_disabled = 2131296270;
			
			// aapt resource value: 0x7f090008
			public const int half_black = 2131296264;
			
			// aapt resource value: 0x7f09000d
			public const int name_black = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int position_gray = 2131296268;
			
			// aapt resource value: 0x7f09000b
			public const int pressed_text_color = 2131296267;
			
			// aapt resource value: 0x7f090003
			public const int task_progress_bg = 2131296259;
			
			// aapt resource value: 0x7f090005
			public const int task_progress_black = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int task_progress_green = 2131296260;
			
			// aapt resource value: 0x7f090006
			public const int task_progress_red = 2131296262;
			
			// aapt resource value: 0x7f090002
			public const int tournament_green = 2131296258;
			
			// aapt resource value: 0x7f090009
			public const int white = 2131296265;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f0a0002
			public const int ActionBar_Size = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int ActionBar_TitleMargin = 2131361795;
			
			// aapt resource value: 0x7f0a0001
			public const int ActionBar_TitleSize = 2131361793;
			
			// aapt resource value: 0x7f0a0020
			public const int AddNewPlayers_buttonHeight = 2131361824;
			
			// aapt resource value: 0x7f0a001e
			public const int AddNewPlayers_buttonTextSize = 2131361822;
			
			// aapt resource value: 0x7f0a0021
			public const int AddNewPlayers_buttonWidth = 2131361825;
			
			// aapt resource value: 0x7f0a0023
			public const int AddNewPlayers_editTextPadding = 2131361827;
			
			// aapt resource value: 0x7f0a001d
			public const int AddNewPlayers_editTextSize = 2131361821;
			
			// aapt resource value: 0x7f0a001f
			public const int AddNewPlayers_imageSize = 2131361823;
			
			// aapt resource value: 0x7f0a0022
			public const int AddNewPlayers_padding = 2131361826;
			
			// aapt resource value: 0x7f0a0019
			public const int AddPlayerItem_imageSize = 2131361817;
			
			// aapt resource value: 0x7f0a001c
			public const int AddPlayerItem_isPlayTextSize = 2131361820;
			
			// aapt resource value: 0x7f0a0015
			public const int AddPlayerItem_marginLeft = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int AddPlayerItem_marginRight = 2131361814;
			
			// aapt resource value: 0x7f0a001b
			public const int AddPlayerItem_nameTextSize = 2131361819;
			
			// aapt resource value: 0x7f0a0017
			public const int AddPlayerItem_paddingBottom = 2131361815;
			
			// aapt resource value: 0x7f0a0018
			public const int AddPlayerItem_paddingTop = 2131361816;
			
			// aapt resource value: 0x7f0a001a
			public const int AddPlayerItem_removeLayoutSize = 2131361818;
			
			// aapt resource value: 0x7f0a006e
			public const int Autorize_ButtonHeigt = 2131361902;
			
			// aapt resource value: 0x7f0a006f
			public const int Autorize_ButtonTextSize = 2131361903;
			
			// aapt resource value: 0x7f0a0070
			public const int Autorize_Margin = 2131361904;
			
			// aapt resource value: 0x7f0a0045
			public const int Bonus_BonusNameTextSize = 2131361861;
			
			// aapt resource value: 0x7f0a0044
			public const int Bonus_BonusNameTextWidth = 2131361860;
			
			// aapt resource value: 0x7f0a0047
			public const int Bonus_ButtonHeight = 2131361863;
			
			// aapt resource value: 0x7f0a0046
			public const int Bonus_ButtonWidth = 2131361862;
			
			// aapt resource value: 0x7f0a0042
			public const int Bonus_CongratsPadingTop = 2131361858;
			
			// aapt resource value: 0x7f0a0041
			public const int Bonus_CongratsTextSize = 2131361857;
			
			// aapt resource value: 0x7f0a003d
			public const int Bonus_ContentPadding = 2131361853;
			
			// aapt resource value: 0x7f0a003e
			public const int Bonus_ImageHeight = 2131361854;
			
			// aapt resource value: 0x7f0a003f
			public const int Bonus_ImageWidth = 2131361855;
			
			// aapt resource value: 0x7f0a0040
			public const int Bonus_MarginBottom = 2131361856;
			
			// aapt resource value: 0x7f0a0043
			public const int Bonus_YouWonBonusTextSize = 2131361859;
			
			// aapt resource value: 0x7f0a0064
			public const int ChoosePhotoButton_Height = 2131361892;
			
			// aapt resource value: 0x7f0a0063
			public const int ChoosePhotoButton_MarginBottom = 2131361891;
			
			// aapt resource value: 0x7f0a0062
			public const int ChoosePhotoButton_TextSize = 2131361890;
			
			// aapt resource value: 0x7f0a0065
			public const int ChoosePhotoLayer_Padding = 2131361893;
			
			// aapt resource value: 0x7f0a0005
			public const int ContentMarginLeftRight = 2131361797;
			
			// aapt resource value: 0x7f0a0006
			public const int ContentMarginTopBottom = 2131361798;
			
			// aapt resource value: 0x7f0a0004
			public const int Dialog_MinWidth = 2131361796;
			
			// aapt resource value: 0x7f0a006a
			public const int DialorRatingButton_Height = 2131361898;
			
			// aapt resource value: 0x7f0a0069
			public const int DialorRatingButton_TextSize = 2131361897;
			
			// aapt resource value: 0x7f0a0068
			public const int DialorRatingLayout_MarginRightLeft = 2131361896;
			
			// aapt resource value: 0x7f0a0067
			public const int DialorRatingLayout_MarginTop = 2131361895;
			
			// aapt resource value: 0x7f0a0066
			public const int DialorRating_TextViewSize = 2131361894;
			
			// aapt resource value: 0x7f0a0074
			public const int EditText_ButtonHeight = 2131361908;
			
			// aapt resource value: 0x7f0a0073
			public const int EditText_EditHeight = 2131361907;
			
			// aapt resource value: 0x7f0a0071
			public const int EditText_Margins = 2131361905;
			
			// aapt resource value: 0x7f0a0072
			public const int EditText_TextSize = 2131361906;
			
			// aapt resource value: 0x7f0a0052
			public const int FirstPalyerItem_HalfImageSize = 2131361874;
			
			// aapt resource value: 0x7f0a0051
			public const int FirstPlayerItem_ImageSize = 2131361873;
			
			// aapt resource value: 0x7f0a0035
			public const int Game_BottomButtonHeight = 2131361845;
			
			// aapt resource value: 0x7f0a0036
			public const int Game_BottomButtonLeftRightMargin = 2131361846;
			
			// aapt resource value: 0x7f0a0037
			public const int Game_BottomButtonTextSize = 2131361847;
			
			// aapt resource value: 0x7f0a0034
			public const int Game_BottomButtonWidth = 2131361844;
			
			// aapt resource value: 0x7f0a0032
			public const int Game_CardButtonHeight = 2131361842;
			
			// aapt resource value: 0x7f0a0033
			public const int Game_CardButtonWidth = 2131361843;
			
			// aapt resource value: 0x7f0a0028
			public const int Game_ContentPaddingLeftRight = 2131361832;
			
			// aapt resource value: 0x7f0a0029
			public const int Game_ContentPaddingTopBottom = 2131361833;
			
			// aapt resource value: 0x7f0a0038
			public const int Game_PointsLayoutHeight = 2131361848;
			
			// aapt resource value: 0x7f0a0039
			public const int Game_PointsSize = 2131361849;
			
			// aapt resource value: 0x7f0a003a
			public const int Game_PointsTextSize = 2131361850;
			
			// aapt resource value: 0x7f0a002d
			public const int Game_TopBarCountScoreTextSize = 2131361837;
			
			// aapt resource value: 0x7f0a002a
			public const int Game_TopBarHeight = 2131361834;
			
			// aapt resource value: 0x7f0a002b
			public const int Game_TopBarImageSize = 2131361835;
			
			// aapt resource value: 0x7f0a002c
			public const int Game_TopBarMargin = 2131361836;
			
			// aapt resource value: 0x7f0a0030
			public const int Game_TopBarPlayerNameTextSize = 2131361840;
			
			// aapt resource value: 0x7f0a0031
			public const int Game_TopBarPlayerPositionTextSize = 2131361841;
			
			// aapt resource value: 0x7f0a002e
			public const int Game_TopBarScoreTextSize = 2131361838;
			
			// aapt resource value: 0x7f0a002f
			public const int Game_TopBarTextMargin = 2131361839;
			
			// aapt resource value: 0x7f0a003b
			public const int Game_x2Size = 2131361851;
			
			// aapt resource value: 0x7f0a003c
			public const int Game_x2TextSize = 2131361852;
			
			// aapt resource value: 0x7f0a0024
			public const int ImageCard_MarginBottom = 2131361828;
			
			// aapt resource value: 0x7f0a0027
			public const int ImageCard_TextHeight = 2131361831;
			
			// aapt resource value: 0x7f0a0026
			public const int ImageCard_TextPadding = 2131361830;
			
			// aapt resource value: 0x7f0a0025
			public const int ImageCard_TextSize = 2131361829;
			
			// aapt resource value: 0x7f0a000a
			public const int MainMenu_linkMarginBottom = 2131361802;
			
			// aapt resource value: 0x7f0a0009
			public const int MainMenu_linkMarginTop = 2131361801;
			
			// aapt resource value: 0x7f0a0008
			public const int MainMenu_linkSize = 2131361800;
			
			// aapt resource value: 0x7f0a0007
			public const int MainMenu_logoSize = 2131361799;
			
			// aapt resource value: 0x7f0a0010
			public const int MainMenu_plusTaskButtonHeight = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int MainMenu_plusTaskButtonTextSize = 2131361809;
			
			// aapt resource value: 0x7f0a000f
			public const int MainMenu_plusTaskButtonWidth = 2131361807;
			
			// aapt resource value: 0x7f0a000d
			public const int MainMenu_startButtonHeight = 2131361805;
			
			// aapt resource value: 0x7f0a000e
			public const int MainMenu_startButtonMarginBottom = 2131361806;
			
			// aapt resource value: 0x7f0a000b
			public const int MainMenu_startButtonTextSize = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int MainMenu_startButtonWidth = 2131361804;
			
			// aapt resource value: 0x7f0a006d
			public const int PickPlayerDialog_ListView_MarginS = 2131361901;
			
			// aapt resource value: 0x7f0a006b
			public const int PickPlayerDialog_TextView_Height = 2131361899;
			
			// aapt resource value: 0x7f0a006c
			public const int PickPlayerDialog_TextView_Size = 2131361900;
			
			// aapt resource value: 0x7f0a005c
			public const int PlayerLeadText_Size = 2131361884;
			
			// aapt resource value: 0x7f0a005d
			public const int PlayerNameText_Size = 2131361885;
			
			// aapt resource value: 0x7f0a005e
			public const int PlayerScoreText_Size = 2131361886;
			
			// aapt resource value: 0x7f0a0012
			public const int PlayersList_buttonHeight = 2131361810;
			
			// aapt resource value: 0x7f0a0014
			public const int PlayersList_buttonTextSize = 2131361812;
			
			// aapt resource value: 0x7f0a0013
			public const int PlayersList_buttonWidth = 2131361811;
			
			// aapt resource value: 0x7f0a005f
			public const int ResultGameButton_Text_Size = 2131361887;
			
			// aapt resource value: 0x7f0a0060
			public const int ResultGameList_MarginBotom = 2131361888;
			
			// aapt resource value: 0x7f0a0061
			public const int ResultGameList_MarginLeftRight = 2131361889;
			
			// aapt resource value: 0x7f0a0000
			public const int RoundedCorners = 2131361792;
			
			// aapt resource value: 0x7f0a005b
			public const int RuleFragment_ContainerTextSize = 2131361883;
			
			// aapt resource value: 0x7f0a005a
			public const int RuleFragment_HeaderTextMarginTopBottom = 2131361882;
			
			// aapt resource value: 0x7f0a0059
			public const int RuleFragment_HeaderTextSize = 2131361881;
			
			// aapt resource value: 0x7f0a0058
			public const int RuleFragment_ImageViewHeight = 2131361880;
			
			// aapt resource value: 0x7f0a0054
			public const int RuleFragment_LayoutMarginBottom = 2131361876;
			
			// aapt resource value: 0x7f0a0056
			public const int RuleFragment_LayoutMarginLeftRight = 2131361878;
			
			// aapt resource value: 0x7f0a0055
			public const int RuleFragment_LayoutMarginTop = 2131361877;
			
			// aapt resource value: 0x7f0a0057
			public const int RuleFragment_LayoutPadding = 2131361879;
			
			// aapt resource value: 0x7f0a0053
			public const int RuleFragment_ScrollImageMarginBottom = 2131361875;
			
			// aapt resource value: 0x7f0a0076
			public const int Store_ContentTextSize = 2131361910;
			
			// aapt resource value: 0x7f0a0079
			public const int Store_Header_Margin = 2131361913;
			
			// aapt resource value: 0x7f0a0075
			public const int Store_Header_TextSize = 2131361909;
			
			// aapt resource value: 0x7f0a0080
			public const int Store_IconContainerSize = 2131361920;
			
			// aapt resource value: 0x7f0a007f
			public const int Store_IconSize = 2131361919;
			
			// aapt resource value: 0x7f0a007b
			public const int Store_List_Margin = 2131361915;
			
			// aapt resource value: 0x7f0a007d
			public const int Store_More_PaddingBottom = 2131361917;
			
			// aapt resource value: 0x7f0a007c
			public const int Store_More_PaddingLeftRight = 2131361916;
			
			// aapt resource value: 0x7f0a007e
			public const int Store_More_TextLeftMargin = 2131361918;
			
			// aapt resource value: 0x7f0a0082
			public const int Store_PricePadding = 2131361922;
			
			// aapt resource value: 0x7f0a0081
			public const int Store_SaleIconSize = 2131361921;
			
			// aapt resource value: 0x7f0a0078
			public const int Store_Scroll_PaddingTop = 2131361912;
			
			// aapt resource value: 0x7f0a007a
			public const int Store_Task_MarginTop = 2131361914;
			
			// aapt resource value: 0x7f0a0077
			public const int Store_WhiteContentView_Margin = 2131361911;
			
			// aapt resource value: 0x7f0a004c
			public const int TaskProgress_ContinueButtonHeight = 2131361868;
			
			// aapt resource value: 0x7f0a004d
			public const int TaskProgress_ContinueButtonWidth = 2131361869;
			
			// aapt resource value: 0x7f0a004f
			public const int TaskProgress_CurrentScoreTextSize = 2131361871;
			
			// aapt resource value: 0x7f0a004b
			public const int TaskProgress_DescTextSize = 2131361867;
			
			// aapt resource value: 0x7f0a0050
			public const int TaskProgress_EndDescTextSize = 2131361872;
			
			// aapt resource value: 0x7f0a0049
			public const int TaskProgress_MarginBottom = 2131361865;
			
			// aapt resource value: 0x7f0a0048
			public const int TaskProgress_MarginTop = 2131361864;
			
			// aapt resource value: 0x7f0a004e
			public const int TaskProgress_ScoreLayoutHeight = 2131361870;
			
			// aapt resource value: 0x7f0a004a
			public const int TaskProgress_TitleTextSize = 2131361866;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int add_new_player = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int add_player_button = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int add_player_button_pressed = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int add_player_button_selector = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int back_button = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int back_button_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int back_button_selector = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int background = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bear_df = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bear_ny = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bonus = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bonus_button_selector = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bonus_sale = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int bonus_sale_25 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bonus_store_icon = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int cancel_button = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int card_backside = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int choose_from_contacts = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int circle_shape = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int continue_button = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int continue_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int delete_button = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int disgusting_df = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int disgusting_ny = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int divider = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int done = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int drink_df = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int drink_ny = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int exchange_df = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int exchange_ny = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int first_player = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int first_player_icon = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int fun_df = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int fun_ny = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int game_background = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int iq_df = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int iq_ny = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int koordination_df = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int koordination_ny = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int light_bottom = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int light_top = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int logo = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int patter_df = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int patter_ny = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int photo_default = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int photo_df = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int photo_ny = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int pic_df = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int pic_ny = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int plus_tasks_button = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int points = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int prost_df = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int prost_ny = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ready_button = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ready_label_enable = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int remove_adb = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int round_rect_shape_grey_background = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int round_rect_shape_white_background = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int round_rect_shape_white_border = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int rules_button = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int rules_one_page = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int rules_one_sroll_page = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int rules_three_page = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int rules_three_sroll_page = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int rules_two_page = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int rules_two_sroll_page = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int shadow = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int shop_background_bottomlight = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int shop_background_toplight = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int shop_bonus_10 = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int shop_bonus_30 = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int shop_bonus_all = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int shop_bonus_background = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int shop_more_background = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int shop_task_10 = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int shop_task_100 = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int shop_task_30 = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int shop_task_70 = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int shop_task_all = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int shop_task_background = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int sms_df = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int sms_ny = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int splash = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int splash_screen = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int start_game_button = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int strength_df = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int strength_ny = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int table_button = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int table_list_background = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int task_sale = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int task_sale_25 = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int task_sale_50 = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int task_sale_70 = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int task_store_icon = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int taskprogress_background = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int x2 = 2130837599;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0c0024
			public const int BoardGame = 2131492900;
			
			// aapt resource value: 0x7f0c0027
			public const int PlusCards = 2131492903;
			
			// aapt resource value: 0x7f0c0026
			public const int Rules = 2131492902;
			
			// aapt resource value: 0x7f0c0025
			public const int StartGame = 2131492901;
			
			// aapt resource value: 0x7f0c0007
			public const int TextView01 = 2131492871;
			
			// aapt resource value: 0x7f0c0060
			public const int addPlayer = 2131492960;
			
			// aapt resource value: 0x7f0c0000
			public const int adjust_height = 2131492864;
			
			// aapt resource value: 0x7f0c0001
			public const int adjust_width = 2131492865;
			
			// aapt resource value: 0x7f0c0011
			public const int bonusContentLayout = 2131492881;
			
			// aapt resource value: 0x7f0c0057
			public const int bonusDescription = 2131492951;
			
			// aapt resource value: 0x7f0c0056
			public const int bonusHeader = 2131492950;
			
			// aapt resource value: 0x7f0c0058
			public const int bonusListView = 2131492952;
			
			// aapt resource value: 0x7f0c0016
			public const int bonusText = 2131492886;
			
			// aapt resource value: 0x7f0c001d
			public const int buttonEasy = 2131492893;
			
			// aapt resource value: 0x7f0c0031
			public const int buttonFrameLayout = 2131492913;
			
			// aapt resource value: 0x7f0c0042
			public const int buttonLayout = 2131492930;
			
			// aapt resource value: 0x7f0c001f
			public const int buttonNo = 2131492895;
			
			// aapt resource value: 0x7f0c001e
			public const int buttonYester = 2131492894;
			
			// aapt resource value: 0x7f0c0008
			public const int cancelButton = 2131492872;
			
			// aapt resource value: 0x7f0c004d
			public const int changeCountScoreText = 2131492941;
			
			// aapt resource value: 0x7f0c0006
			public const int chooseFromContButton = 2131492870;
			
			// aapt resource value: 0x7f0c0018
			public const int choosePhotoButton = 2131492888;
			
			// aapt resource value: 0x7f0c001a
			public const int choosePlayer = 2131492890;
			
			// aapt resource value: 0x7f0c0034
			public const int circle_crop = 2131492916;
			
			// aapt resource value: 0x7f0c0009
			public const int confirmButton = 2131492873;
			
			// aapt resource value: 0x7f0c0013
			public const int congrats = 2131492883;
			
			// aapt resource value: 0x7f0c0020
			public const int contentFrameLayout = 2131492896;
			
			// aapt resource value: 0x7f0c0015
			public const int continueButton = 2131492885;
			
			// aapt resource value: 0x7f0c004f
			public const int currentScoreText = 2131492943;
			
			// aapt resource value: 0x7f0c005f
			public const int customActionButton = 2131492959;
			
			// aapt resource value: 0x7f0c004c
			public const int descLayout = 2131492940;
			
			// aapt resource value: 0x7f0c000b
			public const int doneImage = 2131492875;
			
			// aapt resource value: 0x7f0c004e
			public const int endDescriptionText = 2131492942;
			
			// aapt resource value: 0x7f0c0032
			public const int endGameButton = 2131492914;
			
			// aapt resource value: 0x7f0c003e
			public const int gameContent = 2131492926;
			
			// aapt resource value: 0x7f0c0052
			public const int googleStoreActive = 2131492946;
			
			// aapt resource value: 0x7f0c0051
			public const int googleStoreNotActive = 2131492945;
			
			// aapt resource value: 0x7f0c0038
			public const int imageBackgroundRules = 2131492920;
			
			// aapt resource value: 0x7f0c0021
			public const int imageCardView = 2131492897;
			
			// aapt resource value: 0x7f0c0029
			public const int imagePickPlayer = 2131492905;
			
			// aapt resource value: 0x7f0c003b
			public const int imageScroll = 2131492923;
			
			// aapt resource value: 0x7f0c0012
			public const int imageView = 2131492882;
			
			// aapt resource value: 0x7f0c000e
			public const int isPlayText = 2131492878;
			
			// aapt resource value: 0x7f0c0059
			public const int layout = 2131492953;
			
			// aapt resource value: 0x7f0c0035
			public const int leadText = 2131492917;
			
			// aapt resource value: 0x7f0c0049
			public const int light_bottom = 2131492937;
			
			// aapt resource value: 0x7f0c001b
			public const int linearLayout1 = 2131492891;
			
			// aapt resource value: 0x7f0c0023
			public const int logoImage = 2131492899;
			
			// aapt resource value: 0x7f0c0017
			public const int makePhotoButton = 2131492887;
			
			// aapt resource value: 0x7f0c0044
			public const int makeThisButton = 2131492932;
			
			// aapt resource value: 0x7f0c002a
			public const int namePickPlayer = 2131492906;
			
			// aapt resource value: 0x7f0c0002
			public const int none = 2131492866;
			
			// aapt resource value: 0x7f0c0004
			public const int playerImage = 2131492868;
			
			// aapt resource value: 0x7f0c002b
			public const int playerInGameImage = 2131492907;
			
			// aapt resource value: 0x7f0c002c
			public const int playerInGameName = 2131492908;
			
			// aapt resource value: 0x7f0c002d
			public const int playerInGamePostion = 2131492909;
			
			// aapt resource value: 0x7f0c002e
			public const int playerInGameScore = 2131492910;
			
			// aapt resource value: 0x7f0c0003
			public const int playerLayout = 2131492867;
			
			// aapt resource value: 0x7f0c0019
			public const int playerList = 2131492889;
			
			// aapt resource value: 0x7f0c0005
			public const int playerName = 2131492869;
			
			// aapt resource value: 0x7f0c000d
			public const int playerNameLayout = 2131492877;
			
			// aapt resource value: 0x7f0c0028
			public const int playerPickList = 2131492904;
			
			// aapt resource value: 0x7f0c002f
			public const int playerScore = 2131492911;
			
			// aapt resource value: 0x7f0c0037
			public const int playerTournamentListView = 2131492919;
			
			// aapt resource value: 0x7f0c0010
			public const int playersList = 2131492880;
			
			// aapt resource value: 0x7f0c0046
			public const int points = 2131492934;
			
			// aapt resource value: 0x7f0c005d
			public const int priceText = 2131492957;
			
			// aapt resource value: 0x7f0c0043
			public const int refuseButton = 2131492931;
			
			// aapt resource value: 0x7f0c000c
			public const int removeButton = 2131492876;
			
			// aapt resource value: 0x7f0c000a
			public const int removeLayout = 2131492874;
			
			// aapt resource value: 0x7f0c005b
			public const int saleImageView = 2131492955;
			
			// aapt resource value: 0x7f0c003f
			public const int scoreLayout = 2131492927;
			
			// aapt resource value: 0x7f0c0040
			public const int scoreString = 2131492928;
			
			// aapt resource value: 0x7f0c0036
			public const int scoreText = 2131492918;
			
			// aapt resource value: 0x7f0c0041
			public const int separator = 2131492929;
			
			// aapt resource value: 0x7f0c005c
			public const int shadow = 2131492956;
			
			// aapt resource value: 0x7f0c003d
			public const int startGameLayout = 2131492925;
			
			// aapt resource value: 0x7f0c0033
			public const int startNewGameButton = 2131492915;
			
			// aapt resource value: 0x7f0c000f
			public const int startPlayButton = 2131492879;
			
			// aapt resource value: 0x7f0c004b
			public const int statusDescriptionText = 2131492939;
			
			// aapt resource value: 0x7f0c004a
			public const int statusTitleText = 2131492938;
			
			// aapt resource value: 0x7f0c005a
			public const int storeButton = 2131492954;
			
			// aapt resource value: 0x7f0c0061
			public const int tableButton = 2131492961;
			
			// aapt resource value: 0x7f0c0050
			public const int tableShop = 2131492944;
			
			// aapt resource value: 0x7f0c0054
			public const int taskDescription = 2131492948;
			
			// aapt resource value: 0x7f0c0053
			public const int taskHeader = 2131492947;
			
			// aapt resource value: 0x7f0c0045
			public const int taskImageButton = 2131492933;
			
			// aapt resource value: 0x7f0c0055
			public const int taskListView = 2131492949;
			
			// aapt resource value: 0x7f0c0048
			public const int taskProgressView = 2131492936;
			
			// aapt resource value: 0x7f0c0022
			public const int textCard = 2131492898;
			
			// aapt resource value: 0x7f0c003a
			public const int textContainer = 2131492922;
			
			// aapt resource value: 0x7f0c0039
			public const int textHeader = 2131492921;
			
			// aapt resource value: 0x7f0c001c
			public const int textView1 = 2131492892;
			
			// aapt resource value: 0x7f0c005e
			public const int titleText = 2131492958;
			
			// aapt resource value: 0x7f0c0030
			public const int tournament = 2131492912;
			
			// aapt resource value: 0x7f0c003c
			public const int viewPager = 2131492924;
			
			// aapt resource value: 0x7f0c0047
			public const int x2 = 2131492935;
			
			// aapt resource value: 0x7f0c0014
			public const int youHaveBonus = 2131492884;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int AddNewPlayer = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int AddPlayerItem = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int AddPlayers = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Bonus = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int ChoosePhoto = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ChoosePlayer = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int ChoosePlayerItem = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int DialogRating = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int ImageCard = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int MainMenu = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int PickPlayerDialog = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int PickPlayerItem = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int PlayerInGameItem = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int PlayerItem = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int ResultsGame = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int RuleFragment = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int Rules = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int Splash = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int StartGame = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int Store = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int StoreItem = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int TaskStatus = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int YorshActionBar = 2130968598;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f050000
			public const int gtm_analytics = 2131034112;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060016
			public const int AddNewPlayerLowCaseString = 2131099670;
			
			// aapt resource value: 0x7f060017
			public const int AddNewPlayerString = 2131099671;
			
			// aapt resource value: 0x7f060005
			public const int ApplicationName = 2131099653;
			
			// aapt resource value: 0x7f06002e
			public const int AreYouLikeString = 2131099694;
			
			// aapt resource value: 0x7f06001b
			public const int AreYouShureString = 2131099675;
			
			// aapt resource value: 0x7f060006
			public const int BoardGameString = 2131099654;
			
			// aapt resource value: 0x7f06000f
			public const int BuyString = 2131099663;
			
			// aapt resource value: 0x7f060037
			public const int CancelString = 2131099703;
			
			// aapt resource value: 0x7f060015
			public const int ChooseFromContactString = 2131099669;
			
			// aapt resource value: 0x7f060021
			public const int ChooseFromGalleryString = 2131099681;
			
			// aapt resource value: 0x7f06002a
			public const int CompleteGameString = 2131099690;
			
			// aapt resource value: 0x7f060038
			public const int ConfirmString = 2131099704;
			
			// aapt resource value: 0x7f060033
			public const int CongratString = 2131099699;
			
			// aapt resource value: 0x7f060025
			public const int ContinueString = 2131099685;
			
			// aapt resource value: 0x7f060030
			public const int EasyString = 2131099696;
			
			// aapt resource value: 0x7f06002f
			public const int EstimateUsString = 2131099695;
			
			// aapt resource value: 0x7f06001a
			public const int GameString = 2131099674;
			
			// aapt resource value: 0x7f06000a
			public const int GoToMosigraSite = 2131099658;
			
			// aapt resource value: 0x7f06003a
			public const int GoToSaleString = 2131099706;
			
			// aapt resource value: 0x7f060039
			public const int GoToShopingString = 2131099705;
			
			// aapt resource value: 0x7f060004
			public const int Hello = 2131099652;
			
			// aapt resource value: 0x7f060012
			public const int IsNotPlayString = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int IsPlayString = 2131099665;
			
			// aapt resource value: 0x7f060031
			public const int LaterString = 2131099697;
			
			// aapt resource value: 0x7f060027
			public const int LeadString = 2131099687;
			
			// aapt resource value: 0x7f06003b
			public const int LicenseFailedMessageString = 2131099707;
			
			// aapt resource value: 0x7f060019
			public const int MakePhotoString = 2131099673;
			
			// aapt resource value: 0x7f06001e
			public const int MakeThisString = 2131099678;
			
			// aapt resource value: 0x7f06002b
			public const int NewGameString = 2131099691;
			
			// aapt resource value: 0x7f060032
			public const int NoFunString = 2131099698;
			
			// aapt resource value: 0x7f060013
			public const int NoNameString = 2131099667;
			
			// aapt resource value: 0x7f06001d
			public const int NoString = 2131099677;
			
			// aapt resource value: 0x7f060026
			public const int NotSupportCameraString = 2131099686;
			
			// aapt resource value: 0x7f06000b
			public const int OpenSiteQuestionString = 2131099659;
			
			// aapt resource value: 0x7f060024
			public const int PickPlayerString = 2131099684;
			
			// aapt resource value: 0x7f060014
			public const int PlayerNameString = 2131099668;
			
			// aapt resource value: 0x7f060010
			public const int PlayersString = 2131099664;
			
			// aapt resource value: 0x7f060035
			public const int PleaseSelectThePlayerString = 2131099701;
			
			// aapt resource value: 0x7f060009
			public const int PlusCardsString = 2131099657;
			
			// aapt resource value: 0x7f060022
			public const int PositionPlayerString = 2131099682;
			
			// aapt resource value: 0x7f060036
			public const int PressReadyButtonString = 2131099702;
			
			// aapt resource value: 0x7f06001f
			public const int RefuseString = 2131099679;
			
			// aapt resource value: 0x7f06002d
			public const int ResultsString = 2131099693;
			
			// aapt resource value: 0x7f06000e
			public const int RulesGameString = 2131099662;
			
			// aapt resource value: 0x7f060008
			public const int RulesString = 2131099656;
			
			// aapt resource value: 0x7f060023
			public const int ScoreString = 2131099683;
			
			// aapt resource value: 0x7f060029
			public const int ScoresString = 2131099689;
			
			// aapt resource value: 0x7f06003c
			public const int SendEmailFailedHeaderString = 2131099708;
			
			// aapt resource value: 0x7f06003d
			public const int SendEmailFailedString = 2131099709;
			
			// aapt resource value: 0x7f06002c
			public const int ShareString = 2131099692;
			
			// aapt resource value: 0x7f060018
			public const int StartGameButtonString = 2131099672;
			
			// aapt resource value: 0x7f060007
			public const int StartGameString = 2131099655;
			
			// aapt resource value: 0x7f06000d
			public const int TheLongestBonusString = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int TheLongestTaskString = 2131099660;
			
			// aapt resource value: 0x7f060020
			public const int TournirTableString = 2131099680;
			
			// aapt resource value: 0x7f060028
			public const int WinnerString = 2131099688;
			
			// aapt resource value: 0x7f06003e
			public const int WriteString = 2131099710;
			
			// aapt resource value: 0x7f06001c
			public const int YesString = 2131099676;
			
			// aapt resource value: 0x7f060034
			public const int YouHaveBonusString = 2131099700;
			
			// aapt resource value: 0x7f06004c
			public const int app_id = 2131099724;
			
			// aapt resource value: 0x7f060001
			public const int auth_google_play_services_client_facebook_display_name = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int auth_google_play_services_client_google_display_name = 2131099648;
			
			// aapt resource value: 0x7f060051
			public const int buy_button = 2131099729;
			
			// aapt resource value: 0x7f06003f
			public const int cancelled = 2131099711;
			
			// aapt resource value: 0x7f060002
			public const int common_google_play_services_unknown_issue = 2131099650;
			
			// aapt resource value: 0x7f060045
			public const int error = 2131099717;
			
			// aapt resource value: 0x7f06004d
			public const int exception = 2131099725;
			
			// aapt resource value: 0x7f060042
			public const int hello_user = 2131099714;
			
			// aapt resource value: 0x7f060003
			public const int library_name = 2131099651;
			
			// aapt resource value: 0x7f060049
			public const int no_friends_selected = 2131099721;
			
			// aapt resource value: 0x7f06004a
			public const int no_place_selected = 2131099722;
			
			// aapt resource value: 0x7f060041
			public const int ok = 2131099713;
			
			// aapt resource value: 0x7f060040
			public const int permission_not_granted = 2131099712;
			
			// aapt resource value: 0x7f060047
			public const int photo_post = 2131099719;
			
			// aapt resource value: 0x7f06004b
			public const int pick_seattle_place = 2131099723;
			
			// aapt resource value: 0x7f060053
			public const int quit_button = 2131099731;
			
			// aapt resource value: 0x7f060052
			public const int retry_button = 2131099730;
			
			// aapt resource value: 0x7f060046
			public const int status_update = 2131099718;
			
			// aapt resource value: 0x7f060043
			public const int success = 2131099715;
			
			// aapt resource value: 0x7f060044
			public const int successfully_posted_post = 2131099716;
			
			// aapt resource value: 0x7f06004f
			public const int unlicensed_dialog_body = 2131099727;
			
			// aapt resource value: 0x7f060050
			public const int unlicensed_dialog_retry_body = 2131099728;
			
			// aapt resource value: 0x7f06004e
			public const int unlicensed_dialog_title = 2131099726;
			
			// aapt resource value: 0x7f060048
			public const int you_picked = 2131099720;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0b0001
			public const int Theme_AppTheme = 2131427329;
			
			// aapt resource value: 0x7f0b0000
			public const int Theme_WithoutActionBar = 2131427328;
			
			// aapt resource value: 0x7f0b0002
			public const int WhiteActionBar = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int YourshDialog = 2131427331;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
